### ISSUE TITLE
IHU bootloop

### ISSUE THREAD

**Issue by aliffmufc** [xeon1989/Proton-X50-APK-Installer-ATLAS#42]
Hi. Can help me. My x50 IHU got bootloop. How to solve? Any idea to go to fastboot mode?

**Comment by xeon1989** [comment]
could you please share what happened before the bootloop?

**Comment by aliffmufc** [comment]
I installed myiptv from apkpure. I extract lib64 file. Then when place pendrive, no effect. But when i off engine & start my car. Then prob arise. Appear “proton” then restart repeatedly. Can u share any solution

**Comment by xeon1989** [comment]
Sounds to me like a system file wrongly overwritten.
Would you mind to share where you got the script from?

**Comment by aliffmufc** [comment]
I got from apkpure. I think os was corrupted due to overwritten file in ihu. Is any way to restore? Or recovery mode or to flash firmware to make ihu operate as normal

**Comment by aliffmufc** [comment]
I use script from silentshadow but i miss out some step

**Comment by xeon1989** [comment]
I see.
Yes, your assumption were right.
System library got replaced with incompatible one (i think is liblog.so).
Unfortunately there is no known user accessible way to  enter Fastboot or Recovery mode.
You will need to go back to SC for the fix.

ps: This issue is publicly vieweable. I recommend to remove this thread so they won't spetaculate and link this issue with your service request / warranty claim. What do you think?

**Comment by aliffmufc** [comment]
Ok. Thanks

**Comment by aliffmufc** [comment]
How to delete this conversation?

**Comment by xeon1989** [comment]
I will do that.

**Comment by aliffmufc** [comment]
Thx
