### ISSUE TITLE
Can’t launch script

### ISSUE THREAD

**Issue by thomasyeoh** [xeon1989/Proton-X50-APK-Installer-ATLAS#49]
Hi, after inserting thumb drive with the script into usb port it doesn’t launch. I followed all script download instructions to the T. Current Atlas OS is V.617. There is a new update to V.644 but I did not update. Help needed please!!!! 🙏

**Comment by xeon1989** [comment]
If you're pretty sure the usb and files placed correctly, it could be you're in 607v2. Try downgrade to 617v1 with another guide in my github repo

**Comment by xeon1989** [comment]
Wise move to copy script to usb on Windows.

There is no way to tell if it's running on 617v1 or 617v2 other than the sign where 617v2 simply ignore scripts in usb.
If you upgraded to 617 via OTA after Mar 2023, most likely it's running v2 firmware.

Nevertheless, it's safe to flash v1 firmware in your case.
Even if you're still running v1 firmware, flashing v1 firmware will not bring any changes since the "base" and firmware to flash are the same.

**Comment by xeon1989** [comment]
I noticed from your screenshot that the content of usb contain MacOS folders.
Please remember not to open your USB on MacOS after finish copying files on Windows.

MacOS will generate unwanted files again once inserted USB...
