### ISSUE TITLE
X50 boot animation

### ISSUE THREAD

**Issue by aliffmufc** [xeon1989/Proton-X50-APK-Installer-ATLAS#70]
Hi xeon. Can ask on how to download boot animation script since no link provided? Thanks

**Comment by xeon1989** [comment]
I did not provide such script since it's high risk, unaware user might get their IHU bricked if they do not know what are they doing.
For whoever knows how it works, discussion in this issue might give clues what to change in the script. 

https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/issues/44#issuecomment-1610978583

**Comment by aliffmufc** [comment]
Noted. Thanks for your advice 🙏🏻

**Comment by xeon1989** [comment]
@aliffmufc I just recalled I have another repo talks about bootanimation.

https://github.com/xeon1989/proton-x50-boot-animation

**Comment by aliffmufc** [comment]
Yeah, thanks. But seemingly no link to download those file package 😅

**Comment by xeon1989** [comment]
sudo-monkey made one and I forker from his git.
Try this.

https://github.com/xeon1989/proton-x50-boot-animation
